//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessLub.CMD.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitnessLub.CMD.Languages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to birthData.
        /// </summary>
        public static string BirthData {
            get {
                return ResourceManager.GetString("BirthData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calories.
        /// </summary>
        public static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carbohydrates.
        /// </summary>
        public static string Carbohydrates {
            get {
                return ResourceManager.GetString("Carbohydrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the gender:.
        /// </summary>
        public static string EnterGender {
            get {
                return ResourceManager.GetString("EnterGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a meal.
        /// </summary>
        public static string EnterMeal {
            get {
                return ResourceManager.GetString("EnterMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the.
        /// </summary>
        public static string EnterThe {
            get {
                return ResourceManager.GetString("EnterThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the product name.
        /// </summary>
        public static string EnterTheProductName {
            get {
                return ResourceManager.GetString("EnterTheProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fats.
        /// </summary>
        public static string Fats {
            get {
                return ResourceManager.GetString("Fats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proteins.
        /// </summary>
        public static string Proteins {
            get {
                return ResourceManager.GetString("Proteins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the user name: .
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weight of the portion.
        /// </summary>
        public static string WeightOf {
            get {
                return ResourceManager.GetString("WeightOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome FitnessLub!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do.
        /// </summary>
        public static string WhatDo {
            get {
                return ResourceManager.GetString("WhatDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You ate today.
        /// </summary>
        public static string YouAte {
            get {
                return ResourceManager.GetString("YouAte", resourceCulture);
            }
        }
    }
}
